project:
  type: website
  output-dir: docs

website:
  title: "Biostatistics Master's Thesis"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: sap.html
        text: SAP
      - href: thesis.html
        text: Thesis
      - href: codebook.html
        text: Codebook
      - href: abstract.html
        text: Abstract
format:
  html:
    theme: flatly
    css: styles.css
publish:
  provider: gh-pages
